// Developer Express Code Central Example:
// How to enable Drag and Drop feature in the TableView
// 
// This example shows how to enable Drag and Drop functionality in the
// TableView.
// 
// Please note that if you wish to enable this functionality, it is
// necessary to add a reference to the DevExpress.Xpf.Grid.v12.2.Extensions
// assembly.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E3918

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace How_to_Drag_and_Drop_Between_GridControl_and_Other_Controls.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
