' Developer Express Code Central Example:
' How to enable Drag and Drop feature in the TableView
' 
' This example shows how to enable Drag and Drop functionality in the
' TableView.
' 
' Please note that if you wish to enable this functionality, it is
' necessary to add a reference to the DevExpress.Xpf.Grid.v12.2.Extensions
' assembly.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E3918
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace How_to_Drag_and_Drop_Between_GridControl_and_Other_Controls.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If(How_to_Drag_and_Drop_Between_GridControl_and_Other_Controls.Properties.Resources.resourceMan Is Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(How_to_Drag_and_Drop_Between_GridControl_and_Other_Controls.Properties.Resources).Assembly)
                    How_to_Drag_and_Drop_Between_GridControl_and_Other_Controls.Properties.Resources.resourceMan = temp
                End If

                Return How_to_Drag_and_Drop_Between_GridControl_and_Other_Controls.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return How_to_Drag_and_Drop_Between_GridControl_and_Other_Controls.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                How_to_Drag_and_Drop_Between_GridControl_and_Other_Controls.Properties.Resources.resourceCulture = value
            End Set
        End Property
    End Class
End Namespace
